// ============================================================
//  globalCampaignsData.js
//  20 stand-alone campaigns posted by various community members
//  (separate from user / reporter profile campaigns)
// ============================================================

const portrait = (seed) =>
    `https://images.unsplash.com/photo-${seed}?w=150&h=150&fit=crop&crop=face`;

const postPhoto = (seed) =>
    `https://images.unsplash.com/photo-${seed}?w=800&h=500&fit=crop`;

// ─── Campaign media seeds ─────────────────────────────────────
const photoSeeds = [
    "1465146344240-a2dbf5c7b027", "1504711434969-e33886168f5c", "1488590528505-98d2b5aba04b",
    "1526948128573-703ee1aeb6fa", "1551836022-4196f83abcec", "1464822759023-fed622ff2c3b",
    "1503676260728-1c00da094a0b", "1477959858617-67f85cf4f1a2", "1562774053-0ef85b163c2d",
    "1495020689067-958852a7765e", "1499678567675-2bba5f5e4b1e", "1541963463532-d153efff33ef",
    "1486312338219-ce68d2c6f44d", "1543286386-713bdd548da4", "1518770660439-4636190af475",
    "1517694712202-14dd9538aa97", "1607082348824-0a96f2a4b9da", "1555212697-194d15aa18cf",
    "1511707171634-56260b214de0", "1508739773434-c26b3d09e071",
];

const portraitSeeds = [
    "1535713875002-d1fcc65160e4", "1494790108377-be9c29b29330", "1500648767791-00dcc994a43e",
    "1438761681033-6461ffad8d80", "1472099645785-5658abf4ff4e", "1489424731084-a5d8b06e4923",
    "1527980965255-d3b416303d12", "1544005313-94ddf0286df2", "1507003211169-0a1dd7228f2d",
    "1554151228-14d9def656e4", "1552058544-f2b08422138a", "1580489944761-15a19d654956",
    "1546961342-ea5f62d5a27a", "1521146764736-56c929d59c83", "1531746020798-e6953c6e8e04",
    "1573496359142-b8d87734a5a2", "1519085360753-af0119f7cbe7", "1508214751196-bcfd4ca60f91",
    "1557862921-37829c790f19", "1487412720507-e7ab37603c6f",
];

// ─── 20 unique campaign entries ───────────────────────────────
const campaigns = [
    {
        id: "global_campaign_001",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[0]),
        viewCount: "4.2K",
        postTime: "1h 56m ago",
        status: "active",
        postedBy: { name: "Greenwood PTA", username: "@greenwood_pta", profilePic: portrait(portraitSeeds[0]) },
        title: "Fire at Local School—Your Support Can Bring Relief.",
        description: "A devastating fire has struck our local school, causing significant damage to classrooms and essential supplies. Students and staff are in urgent need of support to rebuild and recover. Your contributions will help restore learning spaces, provide educational materials, and offer emotional support to those affected. Let us unite and bring hope back to our community!",
        amountGoal: "$50,000 Goal",
        raisedAmount: "$48,046 Raised",
        donationCount: "400 Donations",
        location: "Greenwood Elementary School, America",
        categories: ["Education", "Disaster", "Help", "Funding"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[1]), name: "Jordan Hayes", amountRaised: "$4,200" },
            { profilePic: portrait(portraitSeeds[2]), name: "Priya Nair", amountRaised: "$3,800" },
            { profilePic: portrait(portraitSeeds[3]), name: "Marco Bellini", amountRaised: "$2,950" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[4]), userName: "Amanda Cerny", donatedAmount: "$300", words: "I can only imagine the fear and loss these children and teachers must feel. I hope my contribution helps restore their sense of safety and normalcy. Stay strong!" },
            { userProfilePic: portrait(portraitSeeds[5]), userName: "Marcus Webb", donatedAmount: "$150", words: "This community deserves every ounce of support we can give. Donated on behalf of my entire family. Rebuilding takes time but together we will get there soon." },
            { userProfilePic: portrait(portraitSeeds[6]), userName: "Tina Morales", donatedAmount: "$500", words: "No family should face this kind of devastation alone. Every dollar I give represents the belief that our community is stronger together than any disaster or setback." },
        ],
    },
    {
        id: "global_campaign_002",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[1]),
        viewCount: "2.8K",
        postTime: "3h 22m ago",
        status: "active",
        postedBy: { name: "Bayou Relief Fund", username: "@bayou_relief", profilePic: portrait(portraitSeeds[1]) },
        title: "Flood Survivors Need Us—Help Rebuild Their Homes Today.",
        description: "Severe flooding has displaced dozens of families who lost everything in a matter of hours. We are raising funds to provide temporary shelter, clean clothing, and essential household items. Every dollar donated goes directly to families waiting to return home safely. Please give what you can and share this campaign as widely as possible.",
        amountGoal: "$75,000 Goal",
        raisedAmount: "$61,320 Raised",
        donationCount: "512 Donations",
        location: "Bayou Vista, Louisiana, America",
        categories: ["Housing", "Relief", "Community", "Families"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[7]), name: "Sofia Reyes", amountRaised: "$5,100" },
            { profilePic: portrait(portraitSeeds[8]), name: "Tyler Brooks", amountRaised: "$1,750" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[9]), userName: "Derek Osei", donatedAmount: "$75", words: "Small donation but it comes with my biggest prayers. I grew up in a community like this and know how much every single contribution truly matters to survivors." },
            { userProfilePic: portrait(portraitSeeds[10]), userName: "Grace Yuen", donatedAmount: "$250", words: "These stories remind me how fragile and precious our communities are. I am glad there is a platform where people can come together and help so easily." },
            { userProfilePic: portrait(portraitSeeds[11]), userName: "Samuel Knight", donatedAmount: "$400", words: "Donating because I believe in this cause deeply. Let us make sure every affected family knows they are seen, supported, and surrounded by love and genuine care." },
        ],
    },
    {
        id: "global_campaign_003",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[2]),
        viewCount: "6.1K",
        postTime: "5h 10m ago",
        status: "active",
        postedBy: { name: "Lakewood Clean Water", username: "@lakewood_water", profilePic: portrait(portraitSeeds[2]) },
        title: "Clean Water for Lakewood: Fund the New Pipeline Now.",
        description: "Contaminated water has been a crisis in Lakewood for over two years. We are funding the construction of a modern filtration pipeline to deliver clean, safe drinking water to over three thousand residents. This campaign has already gained attention from state legislators and your donation puts real pressure on officials to take decisive action.",
        amountGoal: "$120,000 Goal",
        raisedAmount: "$89,540 Raised",
        donationCount: "730 Donations",
        location: "Lakewood Township, New Jersey, America",
        categories: ["Environment", "Water", "Health", "Infrastructure"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[12]), name: "Aisha Coleman", amountRaised: "$6,300" },
            { profilePic: portrait(portraitSeeds[13]), name: "Liam Foster", amountRaised: "$2,400" },
            { profilePic: portrait(portraitSeeds[14]), name: "Camille Dubois", amountRaised: "$3,150" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[15]), userName: "Fatima Okafor", donatedAmount: "$200", words: "Heartbroken to see this but hopeful because of the outpouring of support. This is what true community looks like. I am proud to be part of this incredible effort." },
            { userProfilePic: portrait(portraitSeeds[16]), userName: "Luke Patterson", donatedAmount: "$100", words: "Shared this campaign with my coworkers and several of them donated too. The ripple effect of kindness is real. Keep pushing forward and do not give up hope." },
            { userProfilePic: portrait(portraitSeeds[17]), userName: "Amanda Cerny", donatedAmount: "$350", words: "Clean water is a human right. It should never be a luxury. I donated and will keep sharing this until every resident in Lakewood has safe water to drink." },
        ],
    },
    {
        id: "global_campaign_004",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[3]),
        viewCount: "1.9K",
        postTime: "7h 45m ago",
        status: "active",
        postedBy: { name: "Virginia Storm Aid", username: "@va_storm_aid", profilePic: portrait(portraitSeeds[3]) },
        title: "After the Storm: Restore Power to Rural Virginia Families.",
        description: "After a powerful storm knocked out power across rural Virginia, dozens of elderly and low-income families are without electricity or heat. Funds raised will cover generator rentals, utility restoration costs, and emergency supply kits for the most vulnerable households in the deeply affected region.",
        amountGoal: "$30,000 Goal",
        raisedAmount: "$22,815 Raised",
        donationCount: "198 Donations",
        location: "Shenandoah Valley, Virginia, America",
        categories: ["Emergency", "Relief", "Rural", "Families"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[4]), name: "Ethan Park", amountRaised: "$4,700" },
            { profilePic: portrait(portraitSeeds[5]), name: "Natalia Voss", amountRaised: "$2,200" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[6]), userName: "Marcus Webb", donatedAmount: "$180", words: "No elderly person should sit in the cold without power. I donated immediately and have been sharing this every day since I first saw it appear in my feed." },
            { userProfilePic: portrait(portraitSeeds[7]), userName: "Tina Morales", donatedAmount: "$275", words: "Rural communities are always the last to receive help after disasters. This campaign is changing that one donation at a time and I am proud to contribute." },
            { userProfilePic: portrait(portraitSeeds[8]), userName: "Derek Osei", donatedAmount: "$90", words: "Sending warmth literally and figuratively. These families deserve better from their government and from all of us. Let us fill in the gap together right now." },
        ],
    },
    {
        id: "global_campaign_005",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[4]),
        viewCount: "3.4K",
        postTime: "12h ago",
        status: "active",
        postedBy: { name: "Chicago School Supply", username: "@chi_supply_drive", profilePic: portrait(portraitSeeds[4]) },
        title: "Books & Backpacks Drive for Under-Resourced Urban Schools.",
        description: "Thousands of students in under-resourced schools start the year without basic supplies. This campaign delivers backpacks, notebooks, pens, and essential reading materials to children who need them most. With your help, we can ensure every child walks into class on the first day feeling prepared and genuinely confident in themselves.",
        amountGoal: "$25,000 Goal",
        raisedAmount: "$23,410 Raised",
        donationCount: "310 Donations",
        location: "South Side Chicago, Illinois, America",
        categories: ["Education", "Youth", "Community", "Funding"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[9]), name: "Diego Romero", amountRaised: "$3,500" },
            { profilePic: portrait(portraitSeeds[10]), name: "Zoe Mitchell", amountRaised: "$4,900" },
            { profilePic: portrait(portraitSeeds[11]), name: "Owen Carter", amountRaised: "$1,600" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[12]), userName: "Grace Yuen", donatedAmount: "$200", words: "Every child deserves to walk into school feeling ready. Donated twice this year. Please share this with every parent and teacher you know right now." },
            { userProfilePic: portrait(portraitSeeds[13]), userName: "Samuel Knight", donatedAmount: "$150", words: "Education is the greatest equalizer. If we can give one child a better start, it ripples through generations. Proud to support this important and timely initiative." },
            { userProfilePic: portrait(portraitSeeds[14]), userName: "Fatima Okafor", donatedAmount: "$300", words: "I was one of those kids who showed up without supplies. This campaign means everything to me personally. Thank you to every single person who has donated so far." },
        ],
    },
    {
        id: "global_campaign_006",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[5]),
        viewCount: "5.7K",
        postTime: "1d ago",
        status: "active",
        postedBy: { name: "Vets First Housing", username: "@vets_first_hsg", profilePic: portrait(portraitSeeds[5]) },
        title: "Veterans' Housing Crisis—Help Our Heroes Find Shelter.",
        description: "Hundreds of veterans in our city are sleeping on the streets despite their service to our nation. This campaign funds transitional housing units, mental health counseling, and job placement services designed specifically for homeless veterans. No one who fought for our freedom should be left without a roof over their head ever.",
        amountGoal: "$200,000 Goal",
        raisedAmount: "$154,800 Raised",
        donationCount: "1,240 Donations",
        location: "Downtown Memphis, Tennessee, America",
        categories: ["Veterans", "Housing", "Health", "Support"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[15]), name: "Isabelle Grant", amountRaised: "$7,200" },
            { profilePic: portrait(portraitSeeds[16]), name: "Noah Rivera", amountRaised: "$5,600" },
            { profilePic: portrait(portraitSeeds[17]), name: "Elena Marsh", amountRaised: "$4,100" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[18]), userName: "Luke Patterson", donatedAmount: "$500", words: "My grandfather was a veteran who struggled with housing. This campaign hits close to home. Every veteran deserves dignity and safety. Thank you all so very much." },
            { userProfilePic: portrait(portraitSeeds[19]), userName: "Amanda Cerny", donatedAmount: "$400", words: "These men and women gave everything for us. The least we can do is ensure they have a safe place to sleep at night. Donating monthly until this goal is met." },
            { userProfilePic: portrait(portraitSeeds[0]), userName: "Marcus Webb", donatedAmount: "$250", words: "Shared this with my entire company and we are doing a matching donation event next Friday. Let us push this campaign over the finish line together as one community." },
        ],
    },
    {
        id: "global_campaign_007",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[6]),
        viewCount: "2.3K",
        postTime: "2d ago",
        status: "active",
        postedBy: { name: "Save Our Center", username: "@save_oak_center", profilePic: portrait(portraitSeeds[6]) },
        title: "Save the Community Center: 40 Years of Service at Risk.",
        description: "Our beloved community center has served families for four decades, offering after-school programs, senior activities, and crisis counseling. Facing severe budget cuts, the center risks permanent closure by the end of this fiscal year. Help us keep the doors open and the lights on for generations to come.",
        amountGoal: "$60,000 Goal",
        raisedAmount: "$38,920 Raised",
        donationCount: "285 Donations",
        location: "East Oakland, California, America",
        categories: ["Community", "Youth", "Seniors", "Funding"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[7]), name: "Caleb Turner", amountRaised: "$3,900" },
            { profilePic: portrait(portraitSeeds[8]), name: "Mei-Lin Huang", amountRaised: "$2,700" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[9]), userName: "Tina Morales", donatedAmount: "$175", words: "I spent my entire childhood at this center. It shaped who I am today. Please help us keep it open for the next generation of kids who need it just as much." },
            { userProfilePic: portrait(portraitSeeds[10]), userName: "Derek Osei", donatedAmount: "$120", words: "Community centers are the backbone of healthy neighborhoods. Losing this one would be a devastating blow to thousands of people who rely on its programs daily." },
            { userProfilePic: portrait(portraitSeeds[11]), userName: "Grace Yuen", donatedAmount: "$220", words: "I moved to this neighborhood because of the center. It is not just a building—it is a lifeline. I will keep donating and sharing until we hit the goal together." },
        ],
    },
    {
        id: "global_campaign_008",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[7]),
        viewCount: "1.5K",
        postTime: "3d ago",
        status: "active",
        postedBy: { name: "Hope for Maria", username: "@hope_for_maria", profilePic: portrait(portraitSeeds[7]) },
        title: "Medical Bills Crushing a Family of Five—Stand With Them.",
        description: "A single mother of five is drowning in medical debt after a cancer diagnosis last spring. She has exhausted her insurance and savings trying to keep her family together during treatment. Every contribution provides direct financial relief to cover hospital bills, rent, and groceries for this remarkable and resilient family.",
        amountGoal: "$40,000 Goal",
        raisedAmount: "$29,650 Raised",
        donationCount: "422 Donations",
        location: "Bronx, New York, America",
        categories: ["Health", "Family", "Relief", "Medical"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[12]), name: "Jasper Williams", amountRaised: "$2,100" },
            { profilePic: portrait(portraitSeeds[13]), name: "Rosa Espinoza", amountRaised: "$1,850" },
            { profilePic: portrait(portraitSeeds[14]), name: "Jordan Hayes", amountRaised: "$3,300" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[15]), userName: "Samuel Knight", donatedAmount: "$300", words: "No parent should have to choose between cancer treatment and keeping the lights on. Donated immediately and telling everyone I know about this urgent campaign." },
            { userProfilePic: portrait(portraitSeeds[16]), userName: "Fatima Okafor", donatedAmount: "$400", words: "Maria is an inspiration. Her strength through this ordeal is extraordinary. I am honored to contribute and hope this reaches every corner of the internet today." },
            { userProfilePic: portrait(portraitSeeds[17]), userName: "Luke Patterson", donatedAmount: "$150", words: "Five kids need their mother. That is all the motivation I needed to donate. Please share this far and wide—let us get this family the relief they urgently deserve." },
        ],
    },
    {
        id: "global_campaign_009",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[8]),
        viewCount: "3.9K",
        postTime: "4d ago",
        status: "completed",
        postedBy: { name: "Reforest NC", username: "@reforest_nc", profilePic: portrait(portraitSeeds[8]) },
        title: "Reforest Our Mountains: Plant 10,000 Trees This Season.",
        description: "Decades of deforestation have left our mountain ecosystem vulnerable to erosion and climate change. This campaign plants ten thousand native trees across degraded slopes, restoring wildlife habitat and improving local water quality. Volunteers are ready and waiting—we just need the funding to purchase and plant every single sapling.",
        amountGoal: "$35,000 Goal",
        raisedAmount: "$35,000 Raised",
        donationCount: "567 Donations",
        location: "Blue Ridge Mountains, North Carolina, America",
        categories: ["Environment", "Climate Crisis", "Science and Discovery", "Community"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[0]), name: "Priya Nair", amountRaised: "$4,500" },
            { profilePic: portrait(portraitSeeds[1]), name: "Tyler Brooks", amountRaised: "$3,200" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[2]), userName: "Amanda Cerny", donatedAmount: "$275", words: "Trees are the lungs of the earth. I am so proud this campaign reached its goal. The work these volunteers put in is absolutely extraordinary and deeply inspiring." },
            { userProfilePic: portrait(portraitSeeds[3]), userName: "Marcus Webb", donatedAmount: "$180", words: "Completed goal! Amazing community effort. I will be following the progress updates and hope to volunteer for the planting event scheduled for next spring season." },
            { userProfilePic: portrait(portraitSeeds[4]), userName: "Tina Morales", donatedAmount: "$350", words: "This gave me genuine hope for the future. When communities rally around environmental causes like this one, real lasting change happens. Incredible work by everyone involved." },
        ],
    },
    {
        id: "global_campaign_010",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[9]),
        viewCount: "4.6K",
        postTime: "5d ago",
        status: "active",
        postedBy: { name: "Justice For All TX", username: "@justice4all_tx", profilePic: portrait(portraitSeeds[9]) },
        title: "Immigrant Families Await Justice—Fund Their Legal Defense.",
        description: "Hundreds of immigrant families are facing deportation without legal representation. This campaign funds experienced immigration attorneys, court filing fees, and translation services for families navigating the complex US immigration system entirely alone. Justice should not depend on how much money you have in your pocket at the time.",
        amountGoal: "$150,000 Goal",
        raisedAmount: "$97,300 Raised",
        donationCount: "880 Donations",
        location: "El Paso, Texas, America",
        categories: ["Justice", "Immigration", "Families", "Legal"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[10]), name: "Sofia Reyes", amountRaised: "$6,800" },
            { profilePic: portrait(portraitSeeds[11]), name: "Aisha Coleman", amountRaised: "$5,100" },
            { profilePic: portrait(portraitSeeds[12]), name: "Marco Bellini", amountRaised: "$3,750" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[13]), userName: "Derek Osei", donatedAmount: "$400", words: "Every family deserves legal representation. This is not a political issue—it is a human rights issue. Donated and encouraged my entire legal network to support this immediately." },
            { userProfilePic: portrait(portraitSeeds[14]), userName: "Grace Yuen", donatedAmount: "$250", words: "The legal system is daunting even for those who speak English. Ensuring families have proper counsel is the bare minimum standard of justice we should demand for all." },
            { userProfilePic: portrait(portraitSeeds[15]), userName: "Samuel Knight", donatedAmount: "$300", words: "Shared this with my law school alumni group. Several colleagues are also signing up to provide pro bono services. Donations plus professional help—let us do this together." },
        ],
    },
    {
        id: "global_campaign_011",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[10]),
        viewCount: "2.1K",
        postTime: "6d ago",
        status: "active",
        postedBy: { name: "Midwest Relief Now", username: "@midwest_relief", profilePic: portrait(portraitSeeds[10]) },
        title: "Emergency Food Relief for Tornado-Ravaged Midwest Towns.",
        description: "Several small Midwest towns were flattened by back-to-back tornadoes last week. Entire neighborhoods are without food, clean water, or shelter. This campaign coordinates emergency food relief boxes, bottled water deliveries, and generator fuel for the families who remain in the affected areas waiting for federal assistance.",
        amountGoal: "$80,000 Goal",
        raisedAmount: "$54,200 Raised",
        donationCount: "640 Donations",
        location: "Joplin, Missouri, America",
        categories: ["Disaster", "Food", "Emergency", "Relief"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[16]), name: "Liam Foster", amountRaised: "$4,300" },
            { profilePic: portrait(portraitSeeds[17]), name: "Camille Dubois", amountRaised: "$2,900" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[18]), userName: "Fatima Okafor", donatedAmount: "$220", words: "I saw the footage and immediately donated. These towns need immediate help right now while the government response catches up. Please share and donate whatever you can." },
            { userProfilePic: portrait(portraitSeeds[19]), userName: "Luke Patterson", donatedAmount: "$175", words: "Natural disasters do not wait for bureaucracy. Community action is faster and more direct. Proud to be part of a movement that actually gets food and water to people." },
            { userProfilePic: portrait(portraitSeeds[0]), userName: "Amanda Cerny", donatedAmount: "$450", words: "Donated to three tornado relief campaigns this month. The scale of destruction is hard to comprehend. Keep this campaign visible—people are still in desperate need right now." },
        ],
    },
    {
        id: "global_campaign_012",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[11]),
        viewCount: "3.2K",
        postTime: "7d ago",
        status: "active",
        postedBy: { name: "Code the Future", username: "@code_future_bmore", profilePic: portrait(portraitSeeds[11]) },
        title: "Tech Lab for Underprivileged Youth—Open the Digital Door.",
        description: "Children in under-resourced communities are being left behind in a digital economy. This campaign equips a fully operational computer lab with thirty stations, coding curriculum, and after-school instructors for students aged eight through eighteen. One lab can change the career trajectory of hundreds of young people every year.",
        amountGoal: "$45,000 Goal",
        raisedAmount: "$31,780 Raised",
        donationCount: "290 Donations",
        location: "West Baltimore, Maryland, America",
        categories: ["Education", "Technology", "Youth", "Startups & Entrepreneurship"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[1]), name: "Ethan Park", amountRaised: "$3,200" },
            { profilePic: portrait(portraitSeeds[2]), name: "Natalia Voss", amountRaised: "$2,600" },
            { profilePic: portrait(portraitSeeds[3]), name: "Diego Romero", amountRaised: "$1,980" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[4]), userName: "Marcus Webb", donatedAmount: "$300", words: "I learned to code on a borrowed laptop and it changed my life completely. Every kid deserves access to these tools. Donated and forwarding this to every developer I know." },
            { userProfilePic: portrait(portraitSeeds[5]), userName: "Tina Morales", donatedAmount: "$250", words: "Digital literacy is the new foundational skill. Campaigns like this one are how we close the opportunity gap one classroom at a time. Incredibly proud to be a supporter." },
            { userProfilePic: portrait(portraitSeeds[6]), userName: "Derek Osei", donatedAmount: "$400", words: "The tech industry talks about diversity but rarely funds access at the source. This is how you actually create diverse pipelines—from the ground up, starting in middle school." },
        ],
    },
    {
        id: "global_campaign_013",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[12]),
        viewCount: "1.7K",
        postTime: "8d ago",
        status: "active",
        postedBy: { name: "Paws of Tucson", username: "@paws_tucson", profilePic: portrait(portraitSeeds[12]) },
        title: "Local Animal Shelter Expansion—More Rooms, More Lives Saved.",
        description: "Our shelter has reached maximum capacity and we are turning animals away every single day. This campaign funds the construction of a new wing with forty additional kennels, a dedicated medical treatment area, and an expanded adoption center. More space means more animals rescued and more families made whole.",
        amountGoal: "$55,000 Goal",
        raisedAmount: "$42,100 Raised",
        donationCount: "375 Donations",
        location: "Tucson, Arizona, America",
        categories: ["Animals", "Community", "Welfare", "Local"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[13]), name: "Zoe Mitchell", amountRaised: "$3,700" },
            { profilePic: portrait(portraitSeeds[14]), name: "Owen Carter", amountRaised: "$2,450" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[15]), userName: "Grace Yuen", donatedAmount: "$180", words: "My dog came from this shelter three years ago and she is my whole world. Happy to give back to the place that brought us together. Every animal deserves a second chance." },
            { userProfilePic: portrait(portraitSeeds[16]), userName: "Samuel Knight", donatedAmount: "$220", words: "Animal welfare is community welfare. The love and responsibility we show to animals reflects the kind of society we want to be. Donated and sharing this everywhere today." },
            { userProfilePic: portrait(portraitSeeds[17]), userName: "Fatima Okafor", donatedAmount: "$140", words: "Shelters do God's work with almost no resources. If this expansion saves even ten more animals from euthanasia each month, every dollar donated is worth it and then some." },
        ],
    },
    {
        id: "global_campaign_014",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[13]),
        viewCount: "2.9K",
        postTime: "9d ago",
        status: "active",
        postedBy: { name: "First Gen Scholars", username: "@firstgen_scholars", profilePic: portrait(portraitSeeds[13]) },
        title: "Scholarships for First-Generation College Students Now.",
        description: "First-generation college students face financial and emotional barriers that their peers never experience. This campaign funds twenty full scholarships covering tuition, housing, textbooks, and mentorship for students from low-income families who have earned their place in higher education through sheer determination and hard work.",
        amountGoal: "$100,000 Goal",
        raisedAmount: "$76,450 Raised",
        donationCount: "690 Donations",
        location: "Flint, Michigan, America",
        categories: ["Education", "Youth", "Funding", "Community"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[18]), name: "Isabelle Grant", amountRaised: "$5,800" },
            { profilePic: portrait(portraitSeeds[19]), name: "Noah Rivera", amountRaised: "$4,100" },
            { profilePic: portrait(portraitSeeds[0]), name: "Elena Marsh", amountRaised: "$3,600" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[1]), userName: "Luke Patterson", donatedAmount: "$350", words: "I was a first-gen student and nearly dropped out in my sophomore year because of finances. Campaigns like this one are literally life-changing. Honored to give back in this way." },
            { userProfilePic: portrait(portraitSeeds[2]), userName: "Amanda Cerny", donatedAmount: "$500", words: "Education should not be a privilege of the wealthy. These scholars earned their spots and deserve full support. Donating monthly to this campaign until every scholarship is funded." },
            { userProfilePic: portrait(portraitSeeds[3]), userName: "Marcus Webb", donatedAmount: "$200", words: "The ripple effect of one scholarship can change an entire family's trajectory over generations. This is one of the most impactful campaigns I have ever supported. Keep going." },
        ],
    },
    {
        id: "global_campaign_015",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[14]),
        viewCount: "1.3K",
        postTime: "10d ago",
        status: "active",
        postedBy: { name: "Rural Health MT", username: "@rural_health_mt", profilePic: portrait(portraitSeeds[14]) },
        title: "Mental Health Clinics for Rural Communities Desperately Needed.",
        description: "Rural Montana has one mental health provider for every three thousand residents. This campaign funds the construction and staffing of three community mental health clinics, bringing counselors, psychiatrists, and crisis support teams to underserved areas that have been overlooked by traditional healthcare infrastructure for decades.",
        amountGoal: "$180,000 Goal",
        raisedAmount: "$88,200 Raised",
        donationCount: "520 Donations",
        location: "Rural Montana, America",
        categories: ["Health", "Mental Health", "Rural", "Community"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[15]), name: "Caleb Turner", amountRaised: "$4,600" },
            { profilePic: portrait(portraitSeeds[16]), name: "Mei-Lin Huang", amountRaised: "$3,100" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[17]), userName: "Tina Morales", donatedAmount: "$300", words: "Mental health is health. Full stop. Rural communities deserve the same quality of care as urban centers. This campaign is addressing a genuine crisis that has gone ignored far too long." },
            { userProfilePic: portrait(portraitSeeds[18]), userName: "Derek Osei", donatedAmount: "$175", words: "I lost a friend to suicide in a rural community with no accessible mental health resources. This campaign is personal to me. Please share and donate whatever you possibly can." },
            { userProfilePic: portrait(portraitSeeds[19]), userName: "Grace Yuen", donatedAmount: "$250", words: "Glad to see this gaining momentum. The mental health crisis in rural America is real and urgent. Every clinic built saves lives. I am donating monthly until the goal is reached." },
        ],
    },
    {
        id: "global_campaign_016",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[15]),
        viewCount: "2.5K",
        postTime: "11d ago",
        status: "active",
        postedBy: { name: "Mural Restoration DC", username: "@dc_mural_restore", profilePic: portrait(portraitSeeds[15]) },
        title: "Restore the Historic Downtown Mural—Preserve Our Heritage.",
        description: "A beloved forty-year-old community mural depicting the history and culture of our neighborhood is deteriorating rapidly. This campaign funds professional restoration, weatherproofing, and a permanent protective covering. The mural is more than paint on a wall—it is our community's living memory and identity preserved for future generations.",
        amountGoal: "$18,000 Goal",
        raisedAmount: "$14,650 Raised",
        donationCount: "180 Donations",
        location: "Washington DC, America",
        categories: ["Heritage", "Arts", "Culture", "Community"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[0]), name: "Jasper Williams", amountRaised: "$1,900" },
            { profilePic: portrait(portraitSeeds[1]), name: "Rosa Espinoza", amountRaised: "$1,400" },
            { profilePic: portrait(portraitSeeds[2]), name: "Jordan Hayes", amountRaised: "$2,100" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[3]), userName: "Samuel Knight", donatedAmount: "$150", words: "Public art tells our collective story. Losing this mural would erase a piece of neighborhood history that cannot be recovered. Grateful this campaign exists to protect it." },
            { userProfilePic: portrait(portraitSeeds[4]), userName: "Fatima Okafor", donatedAmount: "$200", words: "I walk past this mural every single morning. It fills me with pride and joy. Donated because future generations deserve to experience the same feeling that it gives to me." },
            { userProfilePic: portrait(portraitSeeds[5]), userName: "Luke Patterson", donatedAmount: "$100", words: "Art is not a luxury—it is a necessity for healthy communities. Restoring this mural sends a powerful message that we value our history and the people who created it." },
        ],
    },
    {
        id: "global_campaign_017",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[16]),
        viewCount: "7.1K",
        postTime: "12d ago",
        status: "active",
        postedBy: { name: "CA Wildfire Relief", username: "@ca_wildfire_fund", profilePic: portrait(portraitSeeds[16]) },
        title: "Disaster Relief: Wildfire Families Need Your Help Tonight.",
        description: "Rapidly spreading wildfires have forced thousands of California families to evacuate with nothing but the clothes on their backs. This campaign provides immediate emergency housing, food vouchers, clothing, and emotional support services. The need is critical and urgent—every hour of delay means more families sleeping in their cars tonight.",
        amountGoal: "$300,000 Goal",
        raisedAmount: "$218,740 Raised",
        donationCount: "2,100 Donations",
        location: "Northern California, America",
        categories: ["Wildfire", "Disaster", "Emergency", "Families"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[6]), name: "Priya Nair", amountRaised: "$9,200" },
            { profilePic: portrait(portraitSeeds[7]), name: "Marco Bellini", amountRaised: "$7,800" },
            { profilePic: portrait(portraitSeeds[8]), name: "Sofia Reyes", amountRaised: "$6,400" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[9]), userName: "Amanda Cerny", donatedAmount: "$600", words: "The images from the fires are heartbreaking. I donated immediately and have been checking updates every day. Please keep sharing—these families need sustained support for months ahead." },
            { userProfilePic: portrait(portraitSeeds[10]), userName: "Marcus Webb", donatedAmount: "$400", words: "My company is doing a matching campaign tied to this fund. Every dollar donated this week gets doubled. Please give what you can and help us maximize the total impact together." },
            { userProfilePic: portrait(portraitSeeds[11]), userName: "Tina Morales", donatedAmount: "$350", words: "Wildfire season gets worse every year and the need for rapid community response like this only grows. Thank you to every person who donated. You are making a real difference." },
        ],
    },
    {
        id: "global_campaign_018",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[17]),
        viewCount: "1.4K",
        postTime: "13d ago",
        status: "suspended",
        postedBy: { name: "Pool for Pinewood", username: "@pinewood_pool", profilePic: portrait(portraitSeeds[17]) },
        title: "Community Pool Reopening—Safe Summer for Every Child.",
        description: "The Pinewood community pool has been closed for three years following storm damage and budget cuts. This campaign raises funds to repair the filtration system, resurface the pool deck, and hire certified lifeguards for the summer season. Every child in this neighborhood deserves a safe and free place to swim and play.",
        amountGoal: "$42,000 Goal",
        raisedAmount: "$19,300 Raised",
        donationCount: "165 Donations",
        location: "Pinewood, Florida, America",
        categories: ["Community", "Youth", "Recreation", "Local"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[12]), name: "Tyler Brooks", amountRaised: "$2,200" },
            { profilePic: portrait(portraitSeeds[13]), name: "Aisha Coleman", amountRaised: "$1,700" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[14]), userName: "Derek Osei", donatedAmount: "$130", words: "Summer without a pool in Florida is brutal. Every child deserves access to cooling recreation spaces. This campaign is exactly what local community fundraising should look like." },
            { userProfilePic: portrait(portraitSeeds[15]), userName: "Grace Yuen", donatedAmount: "$170", words: "I remember growing up near this pool. It was the heart of the neighborhood in summer. So glad someone started this campaign. Let us get the pool reopened for the kids." },
            { userProfilePic: portrait(portraitSeeds[16]), userName: "Samuel Knight", donatedAmount: "$90", words: "Small communities need small wins like this one to stay cohesive. A reopened pool brings families together and creates memories that last a lifetime. Donating with joy." },
        ],
    },
    {
        id: "global_campaign_019",
        mediaType: "photo",
        mediaUrl: postPhoto(photoSeeds[18]),
        viewCount: "2.0K",
        postTime: "14d ago",
        status: "active",
        postedBy: { name: "Senior Eats Indy", username: "@senior_eats_indy", profilePic: portrait(portraitSeeds[18]) },
        title: "Senior Citizens' Nutrition Program Facing Funding Cuts.",
        description: "A beloved meals-on-wheels style program serving three hundred seniors in Indianapolis is facing a sixty percent funding cut. Without community support, hundreds of elderly residents will lose their only guaranteed daily meal and wellness check. This campaign bridges the funding gap and keeps the program running through the end of the year.",
        amountGoal: "$28,000 Goal",
        raisedAmount: "$21,840 Raised",
        donationCount: "238 Donations",
        location: "Indianapolis, Indiana, America",
        categories: ["Seniors", "Food", "Health", "Community"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[19]), name: "Liam Foster", amountRaised: "$2,800" },
            { profilePic: portrait(portraitSeeds[0]), name: "Camille Dubois", amountRaised: "$2,100" },
            { profilePic: portrait(portraitSeeds[1]), name: "Ethan Park", amountRaised: "$1,650" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[2]), userName: "Fatima Okafor", donatedAmount: "$200", words: "My grandmother relies on a program exactly like this one. The thought of her losing her daily meal and check-in fills me with dread. Donated immediately and sharing every day." },
            { userProfilePic: portrait(portraitSeeds[3]), userName: "Luke Patterson", donatedAmount: "$150", words: "We take care of our seniors or we reveal who we really are as a society. This program is a lifeline for hundreds of people. Please fund it fully before the deadline arrives." },
            { userProfilePic: portrait(portraitSeeds[4]), userName: "Amanda Cerny", donatedAmount: "$300", words: "The people who built our communities deserve to age with dignity and nourishment. This campaign should not even be necessary but I am glad it exists and glad to give today." },
        ],
    },
    {
        id: "global_campaign_020",
        mediaType: "video",
        mediaUrl: postPhoto(photoSeeds[19]),
        viewCount: "1.8K",
        postTime: "15d ago",
        status: "active",
        postedBy: { name: "Kick It Nashville", username: "@kickit_nash", profilePic: portrait(portraitSeeds[19]) },
        title: "Youth Soccer League Needs Equipment and Field Repairs Now.",
        description: "Our youth soccer league serves over four hundred children from low-income families across Nashville. Aging equipment, torn nets, and an uneven playing field are creating safety risks and hampering the program. This campaign replaces all equipment, repairs the field, and funds uniforms for every child for the upcoming season.",
        amountGoal: "$22,000 Goal",
        raisedAmount: "$15,930 Raised",
        donationCount: "190 Donations",
        location: "Nashville, Tennessee, America",
        categories: ["Sports", "Youth", "Community", "Local"],
        fundraisingTeam: [
            { profilePic: portrait(portraitSeeds[5]), name: "Natalia Voss", amountRaised: "$2,400" },
            { profilePic: portrait(portraitSeeds[6]), name: "Diego Romero", amountRaised: "$1,900" },
        ],
        wordsOfSupport: [
            { userProfilePic: portrait(portraitSeeds[7]), userName: "Marcus Webb", donatedAmount: "$175", words: "Sport saved my life as a kid. Giving children a safe field and proper equipment is giving them the gift of discipline, teamwork, and joy. This campaign does exactly that for four hundred kids." },
            { userProfilePic: portrait(portraitSeeds[8]), userName: "Tina Morales", donatedAmount: "$200", words: "My nephew plays in this league. The field conditions are genuinely dangerous. So glad this campaign exists. Let us get these kids a safe place to play as fast as possible." },
            { userProfilePic: portrait(portraitSeeds[9]), userName: "Derek Osei", donatedAmount: "$125", words: "Four hundred kids. Four hundred families. Four hundred futures. That is what this campaign is really about when you think about it. Donated and telling every parent I know." },
        ],
    },
];

export { campaigns as globalCampaigns };
export default campaigns;
